--- #YAML:1.0
name:               Language-Befunge-Storage-Generic-Vec-XS
version:            0.03
abstract:           Language::Befunge::Storage::Generic::Vec rewritten for speed
author:
    - Mark Glines, <mark@glines.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Language::Befunge:    4.00
    Language::Befunge::Vector::XS:  1.1.1
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
